<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_company</name>
   <tag></tag>
   <elementGuidId>76a11f2e-972c-4da4-aee1-6aa4d1388aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0cebe50-29a6-459e-b7ad-9331617c8c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>520acaee-d019-4487-b874-95f12208b045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>c4935189-ed24-45da-abaf-a1592fc0d49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>35edd5f0-d057-4a48-9ded-11190fee8fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>10739538-095a-4357-a60a-0d30d133957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Juara Coding</value>
      <webElementGuid>2ec9d67e-41f4-45c0-8be8-ddb5777574a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>db83a3f3-fc6c-4842-bda3-2cb88c28e971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company&quot;)</value>
      <webElementGuid>8cb10492-ee66-49b6-9537-e3d01200d8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_company']</value>
      <webElementGuid>e6e15078-68a7-4431-984c-9da0035f7427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/span/input</value>
      <webElementGuid>74cec330-8675-422c-ae1d-b0dabbda52b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/input</value>
      <webElementGuid>0f654356-0c05-459f-99d4-3f7f624603fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_company' and @id = 'billing_company']</value>
      <webElementGuid>7659045f-4413-44da-804a-cb0d35202e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
