<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Checkout_icon_bag_alt</name>
   <tag></tag>
   <elementGuidId>cbe7a3be-e78a-4f94-889a-5af67a1ae5a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon_bag_alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8e0ef338-e40f-4851-a725-98a98331dd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_bag_alt</value>
      <webElementGuid>d64a8337-e704-4da4-bbdf-9d3868460ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/i[@class=&quot;icon_bag_alt&quot;]</value>
      <webElementGuid>aa3f6871-699b-4537-87f2-d41ee314dac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      <webElementGuid>eb934982-b9a4-4c0a-be4c-3af0c0c333dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>df0be06f-803b-4c8a-9941-97a235649a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
